### ISSUE TITLE
transfer ownership?

### ISSUE THREAD

**Issue by devoncarew** [devoncarew/language-gn#2]
From this [doc](http://flight-manual.atom.io/behind-atom/sections/maintaining-your-packages/#transferring-ownership), I think the process is:

- I transfer this repo to you
- you publish a new (patch) version

Sounds right? If so, let me know if you're still interested :)

@Alhadis

**Comment by Alhadis** [comment]
Yep, sounds good. :)

**Comment by devoncarew** [comment]
OK, I started the process on my end - you should have an email from github.

**Comment by Alhadis** [comment]
Got it, thanks!
